name: Meme-Auto-Pilot

on:
  workflow_dispatch: # Manual button ke liye
  schedule:
    - cron: '0 6,15 * * *' # Din mein 2 baar (IST: 11:30 AM & 8:30 PM)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install yt-dlp moviepy==1.0.3 requests Pillow

      - name: Download Resources
        run: python downloader.py

      - name: Create Video
        run: python script.py

      # Yahan aap apna YouTube Upload wala logic ya Telegram bot notification daal sakte ho
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: final_meme_short.mp4
          
